-- 코드를 입력하세요
# 자동차 종류 세단 또는 SUV
# 2022-11-01~2022-11-30 대여 가능(HISTORY에 없음), 50만원 <= 대여금액 < 200만원
# CAR_RENTAL_COMPANY_CAR : 차 종류
# CAR_RENTAL_COMPANY_RENTAL_HISTORY : 대여 기록
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN : 할인율
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (1 - P.discount_rate/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ("세단", "SUV") 
AND P.duration_type = "30일 이상"
AND NOT C.CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= 20221101)
AND C.DAILY_FEE * 30 * (1 - P.discount_rate/100) BETWEEN 500000 AND 1999999
GROUP BY C.CAR_ID
ORDER BY 3 DESC, 2, 1 DESC
    