-- 코드를 입력하세요
## 입양일 - 보호일 
SELECT A.ANIMAL_ID, A.NAME
FROM (SELECT I.ANIMAL_ID, I.NAME, DATEDIFF(O.DATETIME, I.DATETIME) AS 기간
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY 기간 DESC) A
LIMIT 2