-- 코드를 입력하세요
# 2021 가입한 회원들 중 상품을 구매한 회원 수, 구매한 회원의 비율

# 2021에 가입한 회원의 수
# SELECT COUNT(*)
# FROM USER_INFO
# WHERE JOINED LIKE "2021%"

SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
    ROUND((COUNT(DISTINCT U.USER_ID)/
        (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE "2021%")), 1) AS PUCHASED_RATIO
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY 1, 2