-- 코드를 입력하세요
SELECT C.FLAVOR
FROM (SELECT A.FLAVOR, A.TOTAL_ORDER, B.INGREDIENT_TYPE
      FROM FIRST_HALF A INNER JOIN ICECREAM_INFO B
      WHERE A.FLAVOR = B.FLAVOR) C
WHERE C.INGREDIENT_TYPE = "fruit_based" AND C.TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC;
      