-- 코드를 입력하세요
# 2022년 8월부터 2022년 10월까지의 COUNT 수가 >= 5 인 것만
# 해당 기간 동안 월별 자동차 아이디 별 대여 횟수
SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
WHERE C.CAR_ID IN (SELECT CC.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CC
    WHERE DATE_FORMAT(CC.START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10"
    GROUP BY CC.CAR_ID
     HAVING COUNT(*) >= 5)
AND DATE_FORMAT(C.START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10"
GROUP BY MONTH, C.CAR_ID
HAVING COUNT(*) != 0
ORDER BY MONTH, C.CAR_ID DESC