-- 코드를 입력하세요
# CAR_ID별로 평균값 도출 DATEDIFF(date1, date2) 사용 -> 5일 이상인 것 도출
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY 2 DESC, 1 DESC