-- 코드를 입력하세요

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE M 
    JOIN REST_REVIEW R 
    JOIN (SELECT MEMBER_ID, RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) AS RANKING
    FROM REST_REVIEW
    GROUP BY MEMBER_ID) RA
    ON M.MEMBER_ID = R.MEMBER_ID 
    AND RA.MEMBER_ID = M.MEMBER_ID
WHERE RA.RANKING = 1
ORDER BY 3, 2
