-- 코드를 입력하세요

SELECT C.AUTHOR_ID, C.AUTHOR_NAME, BOOKS.CATEGORY, BOOKS.TOTAL_SALES
FROM 
(SELECT A.BOOK_ID, A.CATEGORY, A.AUTHOR_ID, SUM(A.PRICE * B.SALES) AS TOTAL_SALES
FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE LIKE "2022-01%"
GROUP BY A.AUTHOR_ID, A.CATEGORY ) BOOKS 
JOIN AUTHOR C ON BOOKS.AUTHOR_ID = C.AUTHOR_ID
ORDER BY C.AUTHOR_ID, BOOKS.CATEGORY DESC