-- 코드를 입력하세요
# SELECT O.PRODUCT_ID, COUNT(*)
# FROM PRODUCT P JOIN OFFLINE_SALE O ON P.PRODUCT_ID = P.PRODUCT_ID
# GROUP BY O.PRODUCT_ID, O.SALES_AMOUNT

# SELECT PRODUCT_ID , SUM(SALES_AMOUNT) AS 개수
# FROM OFFLINE_SALE
# GROUP BY PRODUCT_ID, SALES_AMOUNT


SELECT P.PRODUCT_CODE, (P.PRICE * O.COUNT) AS SALES
FROM PRODUCT P JOIN 
    (SELECT PRODUCT_ID , SUM(SALES_AMOUNT) AS COUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) O
    ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE