-- 코드를 입력하세요
SELECT H.HISTORY_ID, 
      FLOOR(C.DAILY_FEE *(DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1- IFNULL(P.discount_rate, 0)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
AND P.DURATION_TYPE = (
    CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 BETWEEN 7 AND 29 THEN "7일 이상"
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 BETWEEN 30 AND 89 THEN "30일 이상"
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN "90일 이상"
        END
)
WHERE C.CAR_TYPE = "트럭"
ORDER BY FEE DESC, H.HISTORY_ID DESC