-- 코드를 입력하세요
# 세단 중 10월에 대여를 시작한 자동차 리스트 -> 중복 X
SELECT DISTINCT R.CAR_ID
FROM (SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = "세단") R 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON R.CAR_ID = H.CAR_ID
WHERE START_DATE LIKE "2022-10%"
ORDER BY 1 DESC