# -- 코드를 입력하세요
# SELECT CAR_TYPE, COUNT(*) AS CARS
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE LIKE "SUV" OR CAR_TYPE LIKE "세단" OR CAR_TYPE LIKE "트럭"
# GROUP BY CAR_TYPE
# ORDER BY 1

SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE "%통풍시트%" OR OPTIONS LIKE "%열선시트%" OR OPTIONS LIKE "%가죽시트%"
GROUP BY CAR_TYPE
# HAVING CAR_TYPE LIKE "SUV" OR CAR_TYPE LIKE "세단" OR CAR_TYPE LIKE "트럭"
ORDER BY 1